name: Build
on:
  push:
    paths-ignore:
    - "native/**"
    - ".github/workflows/native.yml"
  pull_request:
    paths-ignore:
    - "native/**"
    - ".github/workflows/native.yml"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: windows-latest
            rid: win-x86
          - os: macos-latest
            rid: osx-x64
          - os: macos-latest
            rid: osx-arm64
          - os: ubuntu-latest
            rid: linux-x64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: |
          cd src/NetMiniZ.Tests
          dotnet build -c Release -r ${{ matrix.rid }}
      - name: Test
        if: matrix.rid != 'osx-arm64'
        run: |
          cd src/NetMiniZ.Tests
          dotnet test --runtime ${{ matrix.rid }}
  dispatch:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.repository == 'jsm174/net-miniz' && github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          event-type: build-complete
